### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by cjpf** [jeditt/H3TwitchHooks#7]
Can you provide any installation/setup instructions for this mod?  Alternatively, would you be interested in publishing it to thunderstore?

**Comment by jeditt** [comment]
Hello!

This has been worked on outside of fit, was just posted here to have some
others help me with a few things. I plan on having some version of it out,
or at least separating the slomo and releasing it on Thunderstore, just
have not had the time to research what I need to do to get it to that point.

-tobi

**Comment by cjpf** [comment]
I'm trying to install it and would appreciate some guidance on where the files need to sit.  I'm happy to help contribute by creating real issues on the project as we come across them and help test your work.  

We tried following the instructions here: https://h3vrmodding.miraheze.org/wiki/Manual_Installation

And we cloned your repository into AppData\Roaming\Thunderstore Mod Manager\DataFolder\H3VR\profiles\Default\BepInEx\plugins\H3TwitchHooks\ 
but it doesn't appear to be working this way.

**Comment by jeditt** [comment]
I'll see what I can get figured out. I always compile and zip it manually
on my end and then import it using R2MM's local import feature.

I'm not savvy with coding or GitHub, a lot of this confuses me still. Let
me talk with some of the other modding crew and get back to you.

**Comment by cjpf** [comment]
any updates on this? still looking to build this and use it on my system.

i would be happy to just see some build/compilation instructions

**Comment by jeditt** [comment]
No movement as of yet. I will reach out to some of those who helped me put
it together this week and see what I can do. Sorry, I have had some other
IRL things going on.

**Comment by jeditt** [comment]
Hello!
Sorry for the super long delay here, but I have finally gotten around to pulling this out into its own mod. Very early production, but should run -https://github.com/jeditt/MaxPeen
Right now it is expecting the A/X button on your right controller. I have only tested this on Index at the moment. Future revisions will be pushed there. Just grab the maxpeen.deli file and import it as a local mod in R2MM.
If you want the sound to slow down as well, install cursed.dlls and enable the slow motion option in the configuration files.
-Toby
